# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.4.1
      with:
        badges-directory: .github/badges
        generate-branches-badge: true
        on-missing-report: fail
        fail-if-coverage-less-than: 70%

    - name: Commit and push the badge (if it changed)
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'Commit badge'
        add: '*.svg'
      env:
        REPO_KEY: ${{secrets.PUSH_TOKEN}}
        USERNAME: github-actions[bot]


    - name: Add coverage to PR
      uses: madrapps/jacoco-report@v1.2
      with:
        paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.PUSH_TOKEN }}
        min-coverage-overall: 70
        min-coverage-changed-files: 70


    - name: Upload to Artifactory
      run: mkdir staging && cp target/*.jar staging

    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
